services: docker
language: bash

script:
    - SCRIPT=run_build_image2.sh
    - curl -O https://raw.githubusercontent.com/cyber-dojo-languages/image_builder/master/${SCRIPT}
    - chmod +x ./${SCRIPT}
    - travis_retry ./${SCRIPT} ${PWD}
